# Generated by Django 6.0.4 on 2026-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPageQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_en', models.TextField()),
                ('text_fr', models.TextField()),
            ],
            options={
                'verbose_name': 'Investor Page - Qualification',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvestorPageStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('page', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Investor Page - Strategy',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvestorPageWhyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_en', models.CharField(max_length=150)),
                ('title_fr', models.CharField(max_length=150)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('icon', models.CharField(default='◆', max_length=1)),
            ],
            options={
                'verbose_name': 'Investor Page - Why Card',
                'ordering': ['order'],
            },
        ),
    ]
